### PR TITLE
fix: do not fail if no results using GNU `xargs`

### LINKED ISSUE #189: update_deleted_packages fails on dirname
I'm trying to set up `rules_bazel_integration` test, following the instructions in the project README. When I try to run `update_deleted_packages`, it fails with this error output:

```
$ bazel run @rules_bazel_integration_test//tools:update_deleted_packages
INFO: Analyzed target @rules_bazel_integration_test//tools:update_deleted_packages (131 packages loaded, 544 targets configured).
INFO: Found 1 target...
Target @rules_bazel_integration_test//tools:update_deleted_packages up-to-date:
  bazel-bin/external/rules_bazel_integration_test/tools/update_deleted_packages
INFO: Elapsed time: 28.774s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
dirname: missing operand
Try 'dirname --help' for more information.
```

From what I can tell, one way to hit this error is to attempt to pass a blank/whitespace argument to `dirname`. If I were to guess, somewhere in one of the helpers, a path is constructed to pass to `dirname`, but accidentally ends up blank/empty.

Any advice on how to debug this further would be greatly appreciated. Thank you in advance.

### PR DESCRIPTION
**Pull request by cgrindel**
- Added `-r` flag to `xargs` to ensure that the specified command does not run if there are no results in stdin.
- Use `-I {}` with `xargs` to be cross-platform compatible. This ensures that the command will execute for each result.
- Add `-S 511` to `xargs` to ensure that `xargs` does not fail with `xargs: command line cannot be assembled, too long` if the paths are very long. The default command length for `xargs` is 255. 
- Beefed up the unit tests for `find_child_workspace_packages`.

Closes #189.

### CODE REVIEW

**Comment by cgrindel** [comment]
cc: @mingp @rickeylev

File: tools/shared_fns.sh [hunk 1]
```diff
@@ -31,11 +31,35 @@ filter_bazelignored_directories() {
...
+
 find_workspace_dirs() {
   local path="${1}"
   # Make sure that the -print0 is the last primary for find. Otherwise, you
   # will get undesirable results.
   while IFS=$'\n' read -r line; do filter_bazelignored_directories "${path}" "${line}" ; done < <(
-    find "${path}" \( -name "WORKSPACE" -o -name "WORKSPACE.bazel" \) -print0  | xargs -0 -n 1 dirname
+    # NOTE: If you update the find or xargs flags, be sure to check if those 
+    # changes should be applied to find_bazel_pkgs in find_child_workspace_packages.sh.
+    find "${path}" \( -name "WORKSPACE" -o -name "WORKSPACE.bazel" \) -print0  | \
```
Comment (rickeylev) [inline tools/shared_fns.sh:62]: Just an fyi: I think REPO.bazel is now (or will be) another recognized marker of a workspace boundary.

**Comment by rickeylev** [comment]
Thanks! This is some fun bash and shell scripting :sweat_smile:

File: tools/shared_fns.sh (hunk 1 above)
Comment (cgrindel) [reply tools/shared_fns.sh:62]: It's funny that you mention that. When I was touching this code, I was thinking that this needs to be updated soon. I will find out what the new official markers list is and update this. #272

**Review by katre — APPROVED** [review]
